name: Build and Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.2'
        otp-version: '27.0.1'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Get dependencies and compile
      run: |
        mix deps.get
        mix compile --warnings-as-errors
    - name: Verify formatting
      run: mix format --check-formatted
    - name: Audit dependencies
      run: mix hex.audit
    - name: Run tests
      run: mix test
